### ISSUE TITLE
`notebook.fromJSON` call problems

### ISSUE THREAD

**Issue by jcb91** [captainsafia/split-cell-to-notebook#1]
This is a continuation of https://github.com/ipython-contrib/IPython-notebook-extensions/issues/537, to avoid cluttering it up too much.

To clarify, can I just check the expected workflow is:
1. I have a notebook (let's say the repo example `test-split-cell-to-notebook.ipynb`) which i want to split into two notebooks, either side of the cursor in a given cell (from the source, it seems that this is implicitly the only cell in the notebook, but I think it would make sense to extend this to work with more cells).
2. I place the cursor somewhere in the cell, where I want to split it
3. I click the appropriate toolbar button
4. After the split, I have three notebook tabs open:
   1. the original notebook
   2. `test-split-cell-to-notebook-Copy1.ipynb` (e.g., name chosen by server), which should contain one cell, with the first function definition (`def _handle_kernel_died(self, kernel_id):`)
   3. `test-split-cell-to-notebook-Copy2.ipynb`, which should contain one cell, with the second function definition (`def cwd_for_path(self, path):`)
5. Both of the new notebooks should have all of the same notebook metadata, nbformat, nbformat_minor, etc. as the original version.

Is that right?

As I see it, trying to do all of this from a single instance is not the way forwards. Using the notebook instance `fromJSON` method seems unnecessary. It seems like the notebook object doesn't really support representing more than one notebook - I get warnings about files on disk having changed, because the main notebook instance catches the save, and then compares its own `last_modified` (corresponding to the original file) with the last-modified time of the newly-saved copy (which is what the data in the callback represents). Clearly this was never meant to happen. Equally, instantiating two instances of the class doesn't really work, since it uses DOM elements as part of its own structure, and so new instances add elements based on ids, messing up the page layout.

I think a better way to go about splitting into new notebooks would be to just leverage the contents API directly: we can just call the `save` method directly ([notebook/static/services/contents.js#L164-L177](https://github.com/jupyter/notebook/blob/ebaa23a027783156965273cb7d9bbcdbd0d7c586/notebook/static/services/contents.js#L164-L177)), using data from a `notebook.toJSON` call. Altering the cell to be split can be done directly on the JSON, just using indices to find the correct cell. 

I suppose this does skip triggering the `before_save.Notebook` event ([notebook/static/notebook/js/notebook.js#L2421](https://github.com/jupyter/notebook/blob/ebaa23a027783156965273cb7d9bbcdbd0d7c586/notebook/static/notebook/js/notebook.js#L2421)), but, since we aren't actually trying to save the current notebook, I'm not sure whether it'd add more confusion to trigger it than to leave it untriggered...

**Comment by captainsafia** [comment]
> I have a notebook (let's say the repo example test-split-cell-to-notebook.ipynb) which i want to split into two notebooks, either side of the cursor in a given cell (from the source, it seems that this is implicitly the only cell in the notebook, but I think it would make sense to extend this to work with more cells).

It should work with more cells as is since it operates on the currently selected cell. I haven't laid out my test notebook with multiple cells to confirm that it will work with any selected cell yet though. Good thing to add.

> Is that right?

Yep! :tada: 

> we can just call the save method directly (notebook/static/services/contents.js#L164-L177), using data from a notebook.toJSON call. Altering the cell to be split can be done directly on the JSON, just using indices to find the correct cell.

Do you mean something like [this](https://gist.github.com/captainsafia/bd9df8433865b7b03e4a)? I started working on it but never got around to finishing it. But I think that is the right way to go unless there is messy business with `contents.save` as well.

**Comment by captainsafia** [comment]
Awwwwwww yeahhhhhhh! All done! :tada: You rock!

![You rock!](http://i.giphy.com/xHMIDAy1qkzNS.gif)

**Comment by jcb91** [comment]
haha thanks :stuck_out_tongue:
